version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cqrs
    restart: always
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - db:/database
    command:
      [ "-path", "/database", "-database",  "postgres://postgres:postgres@postgres:5432/cqrs?sslmode=disable", "up" ]

  nats:
    image: nats:latest
    restart: always
