BEGIN TRANSACTION;

DROP TABLE IF EXISTS feeds;

CREATE TABLE feeds (
    id BIGINT PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    creation_date TIMESTAMP NOT NULL 
);

COMMIT TRANSACTION;
